// next-env.d.ts is generated by `next build` and gitignored, so a fresh clone
// typechecks without it. This keeps static image imports typed either way.
/// <reference types="next/image-types/global" />
